import { builtinModules } from "node:module";

const prod = process.argv.includes("production");
const watch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN.
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
	...builtinModules.map((m) => `node:${m}`),
];

async function build() {
	const result = await Bun.build({
		entrypoints: ["./main.ts"],
		outdir: ".",
		target: "browser",
		format: "cjs",
		sourcemap: prod ? "none" : "inline",
		minify: prod,
		external,
		banner,
	});

	if (!result.success) {
		console.error("Build failed:");
		for (const message of result.logs) console.error(message);
		if (!watch) process.exit(1);
		return;
	}
	console.log(`Built main.js${prod ? " (production)" : ""} at ${new Date().toLocaleTimeString()}`);
}

await build();

if (watch) {
	console.log("Watching for changes... (Ctrl+C to stop)");
	const watcher = (await import("fs")).watch(
		import.meta.dir,
		{ recursive: true },
		(_event, filename) => {
			if (!filename) return;
			if (filename.endsWith(".ts") && !filename.includes("node_modules") && filename !== "build.ts") {
				build();
			}
		},
	);
	process.on("SIGINT", () => {
		watcher.close();
		process.exit(0);
	});
}
